# Generated by Django 5.2.15 on 2026-07-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('PC', 'Computadora de Escritorio'), ('LAPTOP', 'Laptop'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('procesador', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=50)),
                ('disco', models.CharField(max_length=100)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('direccion_mac', models.CharField(max_length=50)),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='users.usuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.estadoequipo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.marca')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sistemaoperativo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ubicacion')),
            ],
        ),
    ]
