# Generated by Django 5.2.15 on 2026-06-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO', 'Técnico'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
    ]
